Support grpc updates
Concordium/concordium-client pull request #263
Opened 2023-06-19 14:50 UTC by eb-concordium

## Purpose
Closes https://github.com/Concordium/concordium-client/issues/262.

## Changes

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-06-19 20:53 UTC, abizjak requested changes
Looks good for consensus and block info, but I think birk parameters also need to be updated.

2023-06-19 20:53 UTC, abizjak commented on src/Concordium/Client/GRPC2.hs
> +                _ -> Nothing
I suppose technically we could raise an exception here if only some are set. But I guess we should trust the node and this'll work fine.

2023-06-19 20:53 UTC, abizjak commented on ChangeLog.md
> +- Print "Block time" instead of "Slot time" in the output of `block show`.
What about election difficulty as part of birk parameters? That's also printed as part of `printQueryBirkParameters` and is no longer present.

2023-06-20 09:39 UTC, abizjak commented on ChangeLog.md
> +- Print "Block time" instead of "Slot time" in the output of `block show`.
This was added, so resolving.

2023-06-20 11:31 UTC, abizjak approved these changes

2023-06-20 11:43 UTC, EmilLa1 approved these changes

2023-06-20 11:54 UTC, merged